"""empty message

Revision ID: 04debcbe38ff
Revises: 3dc68f0ab534
Create Date: 2019-04-26 17:37:30.593897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04debcbe38ff'
down_revision = '3dc68f0ab534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_dish',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_dish_dish_id'), 'user_dish', ['dish_id'], unique=False)
    op.create_index(op.f('ix_user_dish_user_id'), 'user_dish', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_dish_user_id'), table_name='user_dish')
    op.drop_index(op.f('ix_user_dish_dish_id'), table_name='user_dish')
    op.drop_table('user_dish')
    # ### end Alembic commands ###
