"""User name table for orders

Revision ID: 293c99b809d2
Revises: 57cd5d69895a
Create Date: 2019-06-11 21:52:58.863818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293c99b809d2'
down_revision = '57cd5d69895a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'user_name')
    # ### end Alembic commands ###