"""Delete name column from users

Revision ID: 6f108114684d
Revises: 21c238e1cc8b
Create Date: 2019-05-14 12:15:27.121627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f108114684d'
down_revision = '21c238e1cc8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
