"""Order phone number

Revision ID: 70f42fa108a8
Revises: cedde5417500
Create Date: 2019-05-16 00:31:43.360473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f42fa108a8'
down_revision = 'cedde5417500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('phone_number', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'phone_number')
    # ### end Alembic commands ###
