"""Notification chats table

Revision ID: 76c41f529ad9
Revises: d197fdba0a32
Create Date: 2019-05-19 12:31:55.976967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c41f529ad9'
down_revision = 'd197fdba0a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_chats',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('chat_title', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('chat_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_chats')
    # ### end Alembic commands ###
