"""Order confirmation date

Revision ID: cedde5417500
Revises: 4d75a25a530b
Create Date: 2019-05-16 00:15:27.325316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cedde5417500'
down_revision = '4d75a25a530b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('confirmation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'confirmation_date')
    # ### end Alembic commands ###
