"""Number field dor categories and dishes
Revision ID: e8c512e9e8b5
Revises: dbfab7289d6a
Create Date: 2019-05-26 18:32:11.184623
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c512e9e8b5'
down_revision = 'dbfab7289d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_categories', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('dishes', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'number')
    op.drop_column('dish_categories', 'number')
    # ### end Alembic commands ###